from django.urls import path, re_path
import re
from .views import (
    UserProfilePackageUpdateView, PackageListView, PackageCreateView, PackageUpdateView,
    UserProfileListView, UserProfileCreateView, UserProfileUpdateView,
    UserCreateView
)

from . import views

urlpatterns = [
    path("", views.kplogin, name="kplogin"),
    path("main", views.kpmain, name="kpmain"),
    path("logout", views.logout_view, name="logout_view"),
    path('blocked-objects/', views.blocked_objects, name='blocked_objects'),
    path("add_domain", views.add_domain, name="add_domain"),
    path("save_domain/<str:domain>", views.save_domain, name="save_domain"),
    path("view_domain/<str:domain>", views.view_domain, name="view_domain"),
    path("volumesnapshots/<str:domain>", views.volumesnapshots, name="volumesnapshots"),
    path("restore_volumesnapshot/<str:domain>/<str:volumesnapshot>", views.restore_volumesnapshot, name="restore_volumesnapshot"),
    path("start_backup/<str:domain>", views.start_backup, name="start_backup"),
    path("settings", views.settings, name="settings"),
    path("livetraffic", views.livetraffic, name="livetraffic"),
    path("delete_domain/<str:domain>", views.delete_domain, name="delete_domain"),
    path("startstop_domain/<str:domain>/<str:action>", views.startstop_domain, name="startstop_domain"),
    path("block_entry/<str:vhost>/<str:x_forwarded_for>/<path:path>/",views.block_entry,name='block_entry'),
    path('pods-status/', views.get_pods_status, name='pods_status'),
    path('tokens/add/', views.add_api_token, name='add_api_token'),
    path('tokens/list/', views.list_api_tokens, name='list_api_tokens'),
    path('tokens/<int:token_id>/delete/', views.delete_api_token, name='delete_api_token'),  # Delete token
    path('zones/create/', views.create_zone, name='create_zone'),
    path('zones/<int:zone_id>/delete/', views.delete_zone, name='delete_zone'),
    path('zones/list/', views.zones_list, name='zones_list'),
    path('records/create/', views.create_dns_record, name='create_dns_record'),
    path('records/<int:record_id>/delete/', views.delete_dns_record, name='delete_dns_record'),  # Delete record
    path("zones/<int:zone_id>/records/", views.list_dns_records, name="list_dns_records"),
    path("ips/manage/", views.manage_ips, name="manage_ips"),
    path("ips/add/", views.add_ip, name="add_ip"),
    path("ips/<int:ip_id>/delete/", views.delete_ip, name="delete_ip"),
    path('users/', views.list_mail_users, name='list_mail_users'),
    path('users/create/', views.create_mail_user, name='create_mail_user'),
    path('users/<int:user_id>/edit/', views.edit_mail_user, name='edit_mail_user'),
    path('users/<int:user_id>/delete/', views.delete_mail_user, name='delete_mail_user'),
    path('domain/<int:pk>/aliases/', views.alias_list,      name='alias_list'),
    path('domain/<int:pk>/aliases/add/', views.alias_add,   name='alias_add'),
    path('aliases/<int:pk>/delete/', views.alias_delete,    name='alias_delete'),
    path('mail-aliases/',views.mail_alias_list,name='mail_alias_list'),
    path('mail-aliases/add/',views.mail_alias_create,name='mail_alias_add'),
    path('mail-aliases/<int:pk>/edit/',views.mail_alias_edit,name='mail_alias_edit'),
    path('mail-aliases/<int:pk>/delete/',views.mail_alias_delete,name='mail_alias_delete'),
    path('firewall-rules/<int:pk>/delete/', views.firewall_rule_delete, name='firewall_rule_delete'),
    path('nodes/',                  views.node_list,   name='node_list'),
    path('nodes/<str:name>/',       views.node_detail, name='node_detail'),
    path('nodes/<str:name>/drain/', views.node_drain,  name='node_drain'),
    path('nodes/<str:name>/cordon/', views.node_cordon, name='node_cordon'),
    path('nodes/<str:name>/uncordon/',views.node_uncordon, name='node_uncordon'),
    path('pods/<str:namespace>/<str:name>/logs/',views.pod_logs,name='pod_logs'),
    path('domains/<str:domain>/backup/<str:jobid>/logs/',views.backup_logs,name='backup_logs'),
    path('domains/<str:domain>/logs/', views.domain_logs, name='domain_logs'),
    path('packages/', PackageListView.as_view(), name='list_packages'),
    path('packages/add/', PackageCreateView.as_view(), name='create_package'),
    path('packages/<int:pk>/edit/', PackageUpdateView.as_view(), name='edit_package'),
    path('profiles/', UserProfileListView.as_view(), name='list_userprofiles'),
    path('profiles/add/', UserProfileCreateView.as_view(), name='create_userprofile'),
    path('profiles/<int:pk>/edit/', UserProfileUpdateView.as_view(), name='edit_userprofile'),
    path('users/add/', UserCreateView.as_view(), name='create_user_with_profile'),
    path('profiles/<int:pk>/edit-package/',UserProfilePackageUpdateView.as_view(),name='edit_userprofile_package'),
]
